// ข้อมูลจำลองข้อสอบ (Seed Data)
export const mockExams = [
  {
    _id: "exam-math-001",
    exam_name: "Mock Exam: คณิตศาสตร์พื้นฐาน",
    description: "ชุดข้อสอบคณิตศาสตร์พื้นฐาน สำหรับทบทวนการคำนวณพื้นฐาน จำนวน 5 ข้อ",
    category: "คณิตศาสตร์",
    time_limit_minutes: 15,
    questions: [
      {
        _id: "q1",
        question_text: "2 + 3 เท่ากับเท่าไหร่?",
        options: [
          { _id: "opt_a", text: "4" },
          { _id: "opt_b", text: "5" },
          { _id: "opt_c", text: "6" },
          { _id: "opt_d", text: "7" },
        ],
        correct_option_id: "opt_b",
        explanation: "2 + 3 = 5",
      },
      {
        _id: "q2",
        question_text: "ผลคูณของ 4 x 5 เท่ากับเท่าไหร่?",
        options: [
          { _id: "opt_a", text: "15" },
          { _id: "opt_b", text: "20" },
          { _id: "opt_c", text: "25" },
          { _id: "opt_d", text: "10" },
        ],
        correct_option_id: "opt_b",
        explanation: "4 x 5 = 20",
      },
      {
        _id: "q3",
        question_text: "รากที่สองของ 16 เท่ากับเท่าไหร่?",
        options: [
          { _id: "opt_a", text: "2" },
          { _id: "opt_b", text: "3" },
          { _id: "opt_c", text: "4" },
          { _id: "opt_d", text: "8" },
        ],
        correct_option_id: "opt_c",
        explanation: "sqrt(16) = 4 เพราะ 4 x 4 = 16",
      },
      {
        _id: "q4",
        question_text: "ถ้า x + 5 = 12, x เท่ากับเท่าไหร่?",
        options: [
          { _id: "opt_a", text: "5" },
          { _id: "opt_b", text: "6" },
          { _id: "opt_c", text: "7" },
          { _id: "opt_d", text: "8" },
        ],
        correct_option_id: "opt_c",
        explanation: "x = 12 - 5 = 7",
      },
      {
        _id: "q5",
        question_text: "เศษของ 17 หารด้วย 5 เท่ากับเท่าไหร่?",
        options: [
          { _id: "opt_a", text: "1" },
          { _id: "opt_b", text: "2" },
          { _id: "opt_c", text: "3" },
          { _id: "opt_d", text: "4" },
        ],
        correct_option_id: "opt_b",
        explanation: "17 = 5 x 3 + 2, เศษคือ 2",
      },
    ],
  },
  {
    _id: "exam-eng-001",
    exam_name: "Mock Exam: English Grammar",
    description: "Basic English Grammar test with 5 questions",
    category: "ภาษาอังกฤษ",
    time_limit_minutes: 10,
    questions: [
      {
        _id: "q1",
        question_text: 'Choose the correct form: "She ___ to school every day."',
        options: [
          { _id: "opt_a", text: "go" },
          { _id: "opt_b", text: "goes" },
          { _id: "opt_c", text: "going" },
          { _id: "opt_d", text: "gone" },
        ],
        correct_option_id: "opt_b",
        explanation: "Third person singular uses 'goes'",
      },
      {
        _id: "q2",
        question_text: 'Which word is a noun? "The cat sat on the mat."',
        options: [
          { _id: "opt_a", text: "sat" },
          { _id: "opt_b", text: "on" },
          { _id: "opt_c", text: "cat" },
          { _id: "opt_d", text: "the" },
        ],
        correct_option_id: "opt_c",
        explanation: "'cat' is a noun (a thing/animal)",
      },
      {
        _id: "q3",
        question_text: 'What is the past tense of "run"?',
        options: [
          { _id: "opt_a", text: "runned" },
          { _id: "opt_b", text: "ran" },
          { _id: "opt_c", text: "running" },
          { _id: "opt_d", text: "runs" },
        ],
        correct_option_id: "opt_b",
        explanation: "The past tense of 'run' is 'ran' (irregular verb)",
      },
      {
        _id: "q4",
        question_text: '"___ is your name?" - "My name is John."',
        options: [
          { _id: "opt_a", text: "What" },
          { _id: "opt_b", text: "Where" },
          { _id: "opt_c", text: "How" },
          { _id: "opt_d", text: "Why" },
        ],
        correct_option_id: "opt_a",
        explanation: "'What' is used to ask about things/names",
      },
      {
        _id: "q5",
        question_text: 'Choose the correct article: "I have ___ apple."',
        options: [
          { _id: "opt_a", text: "a" },
          { _id: "opt_b", text: "an" },
          { _id: "opt_c", text: "the" },
          { _id: "opt_d", text: "no article needed" },
        ],
        correct_option_id: "opt_b",
        explanation: "Use 'an' before words starting with a vowel sound",
      },
    ],
  },
  {
    _id: "exam-cs-001",
    exam_name: "Mock Exam: Computer Science 101",
    description: "Basic computer science concepts test, 5 questions",
    category: "Computer Science",
    time_limit_minutes: 10,
    questions: [
      {
        _id: "q1",
        question_text: "CPU ย่อมาจากคำว่าอะไร?",
        options: [
          { _id: "opt_a", text: "Central Processing Unit" },
          { _id: "opt_b", text: "Computer Personal Unit" },
          { _id: "opt_c", text: "Central Program Utility" },
          { _id: "opt_d", text: "Computer Processing Unit" },
        ],
        correct_option_id: "opt_a",
        explanation: "CPU = Central Processing Unit หน่วยประมวลผลกลาง",
      },
      {
        _id: "q2",
        question_text: " RAM หมายถึงอะไร?",
        options: [
          { _id: "opt_a", text: "Random Access Memory" },
          { _id: "opt_b", text: "Read Access Memory" },
          { _id: "opt_c", text: "Random Action Memory" },
          { _id: "opt_d", text: "Read Action Memory" },
        ],
        correct_option_id: "opt_a",
        explanation: "RAM = Random Access Memory หน่วยความจำหลัก",
      },
      {
        _id: "q3",
        question_text: "ภาษาโปรแกรมใดต่อไปนี้เป็น interpreted language?",
        options: [
          { _id: "opt_a", text: "C" },
          { _id: "opt_b", text: "Python" },
          { _id: "opt_c", text: "Rust" },
          { _id: "opt_d", text: "Go" },
        ],
        correct_option_id: "opt_b",
        explanation: "Python เป็น interpreted language ส่วน C, Rust, Go เป็น compiled",
      },
      {
        _id: "q4",
        question_text: "HTML ใช้สำหรับทำอะไร?",
        options: [
          { _id: "opt_a", text: "สร้างหน้าเว็บ" },
          { _id: "opt_b", text: "คำนวณตัวเลข" },
          { _id: "opt_c", text: "จัดการฐานข้อมูล" },
          { _id: "opt_d", text: "สร้างเกม" },
        ],
        correct_option_id: "opt_a",
        explanation: "HTML = HyperText Markup Language ใช้สร้างโครงสร้างหน้าเว็บ",
      },
      {
        _id: "q5",
        question_text: "SQL ย่อมาจากอะไร?",
        options: [
          { _id: "opt_a", text: "Structured Query Language" },
          { _id: "opt_b", text: "Simple Query Language" },
          { _id: "opt_c", text: "Standard Query Logic" },
          { _id: "opt_d", text: "System Query Language" },
        ],
        correct_option_id: "opt_a",
        explanation: "SQL = Structured Query Language ภาษาสำหรับจัดการฐานข้อมูล",
      },
    ],
  },
];
